DEFINE DATABASE {{ db }};
DEFINE SCHEMA {{ db }}.RAW;

DEFINE TABLE {{ db }}.RAW.CONTACTS (
    CONTACT_ID  VARCHAR,
    FULL_NAME   VARCHAR,
    PHONE_RAW   VARCHAR,
    PHONE_E164  VARCHAR,
    LOADED_AT   TIMESTAMP_NTZ
);
